"""Añadir campo email_confirmado a Usuario

Revision ID: 2455230fdb5a
Revises: 
Create Date: 2025-09-03 22:56:59.751763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2455230fdb5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito_compras', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['id_usuario'])

    with op.batch_alter_table('detalle_carrito', schema=None) as batch_op:
        batch_op.alter_column('id_carrito',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['id_carrito', 'id_producto'])

    with op.batch_alter_table('detalle_pedidos', schema=None) as batch_op:
        batch_op.alter_column('id_pedido',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmado', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('variantes_producto', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variantes_producto', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('email_confirmado')

    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('detalle_pedidos', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_pedido',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('detalle_carrito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_carrito',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('carrito_compras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###

